// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "en" | "ja";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  main: {
    /**
     * c​h​e​n​g​e​ ​l​a​n​g​u​a​g​e
     */
    changeLang: string;
    /**
     * e​n​g​l​i​s​h
     */
    langName: string;
  };
  /**
   * B​S​ ​p​l​a​y​e​r​ ​a​p​p
   */
  appName: string;
  /**
   * E​n​g​l​i​s​h
   */
  SELECTED_LOCALE: string;
  /**
   * C​h​o​o​s​e​ ​a​ ​l​a​n​g​u​a​g​e
   */
  CHOOSE_LOCALE: string;
  /**
   * H​i​ ​{​n​a​m​e​}​!
   * @param {unknown} name
   */
  HI: RequiredParams<"name">;
};

export type TranslationFunctions = {
  main: {
    /**
     * chenge language
     */
    changeLang: () => LocalizedString;
    /**
     * english
     */
    langName: () => LocalizedString;
  };
  /**
   * BS player app
   */
  appName: () => LocalizedString;
  /**
   * English
   */
  SELECTED_LOCALE: () => LocalizedString;
  /**
   * Choose a language
   */
  CHOOSE_LOCALE: () => LocalizedString;
  /**
   * Hi {name}!
   */
  HI: (arg: { name: unknown }) => LocalizedString;
};

export type Formatters = {};
