// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	main: {
		/**
		 * c​h​e​n​g​e​ ​l​a​n​g​u​a​g​e
		 */
		changeLang: string
		/**
		 * e​n​g​l​i​s​h
		 */
		langName: string
		/**
		 * S​e​l​e​c​t​ ​B​e​a​t​ ​S​a​b​e​r​ ​M​a​p​s​ ​F​o​l​d​e​r
		 */
		'Select Beat Saber Maps Folder': string
	}
	langs: {
		/**
		 * E​n​g​l​i​s​h
		 */
		SELECTED_LOCALE: string
		/**
		 * C​h​o​o​s​e​ ​a​ ​l​a​n​g​u​a​g​e
		 */
		CHOOSE_LOCALE: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		langage: string
	}
	/**
	 * B​S​ ​p​l​a​y​e​r​ ​a​p​p
	 */
	appName: string
	/**
	 * H​i​ ​{​n​a​m​e​}​!
	 * @param {unknown} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * P​l​a​y​ ​M​u​s​i​c
	 */
	play_music: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	loading: string
}

export type TranslationFunctions = {
	main: {
		/**
		 * chenge language
		 */
		changeLang: () => LocalizedString
		/**
		 * english
		 */
		langName: () => LocalizedString
		/**
		 * Select Beat Saber Maps Folder
		 */
		'Select Beat Saber Maps Folder': () => LocalizedString
	}
	langs: {
		/**
		 * English
		 */
		SELECTED_LOCALE: () => LocalizedString
		/**
		 * Choose a language
		 */
		CHOOSE_LOCALE: () => LocalizedString
		/**
		 * Language
		 */
		langage: () => LocalizedString
	}
	/**
	 * BS player app
	 */
	appName: () => LocalizedString
	/**
	 * Hi {name}!
	 */
	HI: (arg: { name: unknown }) => LocalizedString
	/**
	 * Play Music
	 */
	play_music: () => LocalizedString
	/**
	 * Loading...
	 */
	loading: () => LocalizedString
}

export type Formatters = {}
