// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorLeft } from "./ColorLeft";
import type { ColorRight } from "./ColorRight";

export interface CustomData2 {
  _editorOffset: bigint;
  _editorOldOffset: bigint;
  _suggestions: Array<string>;
  _colorRight: ColorRight;
  _colorLeft: ColorLeft;
}
