// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Editors } from "./Editors";

export interface CustomData {
  _editors: Editors;
}
