// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifficultyBeatmap } from "./DifficultyBeatmap";

export interface DifficultyBeatmapSet {
  _beatmapCharacteristicName: string;
  _difficultyBeatmaps: Array<DifficultyBeatmap>;
}
