// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomData2 } from "./CustomData2";

export interface DifficultyBeatmap {
  _difficulty: string;
  _difficultyRank: bigint;
  _beatmapFilename: string;
  _noteJumpMovementSpeed: bigint;
  _noteJumpStartBeatOffset: number;
  _customData: CustomData2;
}
