// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChroMapper } from "./ChroMapper";
import type { Mma2 } from "./Mma2";

export interface Editors {
  _lastEditedBy: string;
  MMA2: Mma2;
  ChroMapper: ChroMapper;
}
