// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SongData {
  music_file: string;
  music_name: string;
  music_dir: string;
  mapper: string;
  auther: string;
  image: string;
  length_of_music: number;
}
