// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SongInfoDat {
  song_name: string;
  song_auther: string;
  mapper: string;
  bpm: number;
  song_file_name: string;
  cover_image: string;
}
