# Working example showing how to use nextest to reuse builds and partition test runs on GitHub Actions.
# See workflow runs at https://github.com/nextest-rs/reuse-build-partition-example/actions/workflows/ci.yml.

name: rust_CI

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]
  schedule:
    # Run this every day at 01:00 UTC.
    - cron: 0 1 * * *

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests-partitioned:
    name: Run tests with partitioning
    runs-on: ubuntu-latest
    # needs: build-test-artifacts
    strategy:
      matrix:
        partition: [1, 2]
    steps:
      # The source directory must be checked out.
      - uses: actions/checkout@v4
        with:
          # By default actions/checkout checks out a merge commit. Check out the PR head instead.
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      # In this example, the Rust toolchain is not installed. cargo nextest's run phase does not
      # require Cargo. You can choose to install Rust if your tests require it, of course.
      # Instead, create ~/.cargo/bin as required by the install action.
      - run: mkdir -p ~/.cargo/bin
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: nextest-archive
      - name: Run tests
        working-directory: ./src-tauri
        run: |
          ~/.cargo/bin/cargo-nextest nextest run --archive-file nextest-archive.tar.zst \
            --partition count:${{ matrix.partition }}/2
