# Working example showing how to use nextest to reuse builds and partition test runs on GitHub Actions.
# See workflow runs at https://github.com/nextest-rs/reuse-build-partition-example/actions/workflows/ci.yml.
name: Rust_CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src-tauri

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: install desp lib
        run: apt-get install -y libwebkit2gtk-4.0-dev build-essential wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Build test
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Lint with clippy
        run: cargo clippy --all-targets --all-features
      - name: Check formatting
        run: cargo fmt --all --check
