# Working example showing how to use nextest to reuse builds and partition test runs on GitHub Actions.
# See workflow runs at https://github.com/nextest-rs/reuse-build-partition-example/actions/workflows/ci.yml.

name: rust_CI

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_cache:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cargo
      - name: install libgtk-3-dev
        run: sudo apt-get install libgtk-3-dev
      - name: build
        run: cargo build
        working-directory: src-tauri

  fmt:
    runs-on: ubuntu-latest
    needs: build_cache
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - uses: ./.github/actions/cache_cargo
      - name: fmt
        run: cargo fmt --all -- --check
        working-directory: src-tauri

  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    needs: build_cache
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - uses: ./.github/actions/cache_cargo
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: src-tauri

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    needs: build_cache
    steps:
      - name: create database for test
        run: PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE test"
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cargo
      - name: test
        run: cargo test --all -- --nocapture
        working-directory: src-tauri
